'''Takes in documents from the National Database and spits it out with SQLModel and FastAPI'''
from sqlmodel import Session, Field, select, SQLModel
from typing import Optional
from rich.console import Console
from rich.table import Table
from database import *
from model.contract import *
from model.enrollment import *
from model.master import *
import csv
import sqlite3
import typer
import time

app = typer.Typer(help = "CLI for Patrician from the commandline.")
console = Console()

def play_successful_message(good: bool = True):
	message_start = "Execute: "
	if good:
		ending = typer.style("successful", fg = typer.colors.GREEN, bold=True)
	else:
		ending = typer.style("failure", fg = typer.colors.WHITE, bg=typer.colors.RED)
	message = message_start + ending
	typer.echo(message)

@app.command()
def example():
	connection = sqlite3.connect('db.db')
	cursor = connection.cursor()
	sql_command = "SELECT * FROM enrollment INNER JOIN contract ON enrollment.Contract_Plan = contract.Contract_Plan ORDER BY enrollment DESC LIMIT 1"
	rows = cursor.execute(sql_command).fetchall()
	print(rows)
	connection.commit()
	connection.close()
	play_successful_message()

@app.command()
def drop_all():
	connection = sqlite3.connect('db.db')
	cursor = connection.cursor()
	cursor.execute("DROP TABLE IF EXISTS 'contracts';")
	play_successful_message()
	cursor.execute("DROP TABLE IF EXISTS 'master';")
	play_successful_message()
	cursor.execute("DROP TABLE IF EXISTS '2023_06';")
	play_successful_message()
	cursor.execute("DROP TABLE IF EXISTS '2023_05';")
	play_successful_message()
	cursor.execute("DROP TABLE IF EXISTS '2023_04';")
	play_successful_message()
	cursor.execute("DROP TABLE IF EXISTS '2023_03';")
	play_successful_message()
	cursor.execute("DROP TABLE IF EXISTS '2023_02';")
	play_successful_message()
	cursor.execute("DROP TABLE IF EXISTS '2023_01';")
	play_successful_message()
	
	cursor.execute("DROP TABLE IF EXISTS '2022_12';")
	play_successful_message()
	cursor.execute("DROP TABLE IF EXISTS '2022_11';")
	play_successful_message()
	connection.commit()
	connection.close()

@app.command()
def county(county: str):
	connection = sqlite3.connect('db.db')
	cursor = connection.cursor()
	county = county.title()
	rows = cursor.execute("SELECT * FROM enrollment INNER JOIN contract ON enrollment.Contract_Plan = contract.Contract_Plan WHERE County = '" + (county) + "' ORDER BY enrollment DESC LIMIT 100").fetchall()
	print(rows)
	connection.commit()
	connection.close()
	play_successful_message()

# @app.command()
# def marketing_name(OrganizationMarketingName: str):
	# connection = sqlite3.connect('db.db')
	# cursor = connection.cursor()
	# rows = cursor.execute("SELECT * FROM enrollment INNER JOIN contract ON enrollment.Contract_Plan = contract.Contract_Plan WHERE contract.OrganizationMarketingName = '" + (OrganizationMarketingName) + "' ORDER BY enrollment DESC LIMIT 100").fetchall()
	# print(rows)
	# connection.commit()
	# connection.close()
	# play_successful_message()

@app.command()
def state(state: str):
	connection = sqlite3.connect('db.db')
	cursor = connection.cursor()
	rows = cursor.execute("SELECT * FROM enrollment INNER JOIN contract ON enrollment.Contract_Plan = contract.Contract_Plan WHERE State = '" + (state) + "' ORDER BY enrollment DESC LIMIT 100").fetchall()
	print(rows)
	connection.commit()
	connection.close()
	play_successful_message()

@app.command()
def contract_plan(contract_plan: str):
	connection = sqlite3.connect('db.db')
	cursor = connection.cursor()
	rows = cursor.execute("SELECT * FROM enrollment INNER JOIN contract ON enrollment.Contract_Plan = contract.Contract_Plan WHERE enrollment.Contract_Plan = '" + (contract_plan) + "' ORDER BY enrollment DESC LIMIT 100").fetchall()
	print(rows)
	connection.commit()
	connection.close()
	play_successful_message()

@app.command()
def contract(contract: str):
	connection = sqlite3.connect('db.db')
	cursor = connection.cursor()
	rows = cursor.execute("SELECT * FROM enrollment INNER JOIN contract ON enrollment.Contract_Plan = contract.Contract_Plan WHERE enrollment.ContractID = '" + (contract) + "' ORDER BY enrollment DESC LIMIT 100").fetchall()
	print(rows)
	connection.commit()
	connection.close()
	play_successful_message()

@app.command()
def show():
	connection = sqlite3.connect('db.db')
	cursor = connection.cursor()
	sql_command = "SELECT enrollment, State, County FROM enrollment INNER JOIN contract ON enrollment.Contract_Plan = contract.Contract_Plan ORDER BY enrollment DESC LIMIT 10"
	rows = cursor.execute(sql_command).fetchall()
	
	list = [['Cat', '7', 'Female'],
	['Dog', '0.5', 'Male'],
	['Guinea Pig', '5', 'Male']]
	
	table = Table(show_header=True, header_style="bold blue")
	table.add_column("#", style="dim", width=6)
	table.add_column("State", min_width = 10)
	table.add_column("County", min_width = 20, justify = "right")

	for row in zip(*list):
		table.add_row(*row)
	connection.commit()
	connection.close()
	console.print(table)
	play_successful_message()

@app.command()
def init():
	connection = sqlite3.connect('db.db')
	cursor = connection.cursor()
	create_db_and_tables()

	import_contract_2023_05()
	import_enrollment_2023_05()
	cursor.execute("DELETE FROM Enrollment_2023_05 WHERE enrollment = '*'")
	cursor.execute("DELETE FROM Enrollment_2023_05 WHERE enrollment = 'Enrollment'")
	cursor.execute("ALTER TABLE Enrollment_2023_05 DROP COLUMN SSAStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2023_05 DROP COLUMN FIPSStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2023_05 ADD COLUMN 'Date' DATE DEFAULT '2023-05-15'")
	cursor.execute("ALTER TABLE Enrollment_2023_05 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Enrollment_2023_05 SET 'contractid_planid' = contractid || '' || planid")
	cursor.execute("ALTER TABLE Contract_2023_05 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Contract_2023_05 SET 'contractid_planid' = contractid || '' || planid")
	connection.commit()
	play_successful_message()

	import_contract_2023_04()
	import_enrollment_2023_04()
	cursor.execute("DELETE FROM Enrollment_2023_04 WHERE enrollment = '*'")
	cursor.execute("DELETE FROM Enrollment_2023_04 WHERE enrollment = 'Enrollment'")
	cursor.execute("ALTER TABLE Enrollment_2023_04 DROP COLUMN SSAStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2023_04 DROP COLUMN FIPSStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2023_04 ADD COLUMN 'Date' DATE DEFAULT '2023-04-15'")
	cursor.execute("ALTER TABLE Enrollment_2023_04 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Enrollment_2023_04 SET 'contractid_planid' = contractid || '' || planid")
	cursor.execute("ALTER TABLE Contract_2023_04 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Contract_2023_04 SET 'contractid_planid' = contractid || '' || planid")
	connection.commit()
	play_successful_message()

	import_contract_2023_03()
	import_enrollment_2023_03()
	cursor.execute("DELETE FROM Enrollment_2023_03 WHERE enrollment = '*'")
	cursor.execute("DELETE FROM Enrollment_2023_03 WHERE enrollment = 'Enrollment'")
	cursor.execute("ALTER TABLE Enrollment_2023_03 DROP COLUMN SSAStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2023_03 DROP COLUMN FIPSStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2023_03 ADD COLUMN 'Date' DATE DEFAULT '2023-03-15'")
	cursor.execute("ALTER TABLE Enrollment_2023_03 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Enrollment_2023_03 SET 'contractid_planid' = contractid || '' || planid")
	cursor.execute("ALTER TABLE Contract_2023_03 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Contract_2023_03 SET 'contractid_planid' = contractid || '' || planid")
	connection.commit()
	play_successful_message()

	import_contract_2023_02()
	import_enrollment_2023_02()
	cursor.execute("DELETE FROM Enrollment_2023_02 WHERE enrollment = '*'")
	cursor.execute("DELETE FROM Enrollment_2023_02 WHERE enrollment = 'Enrollment'")
	cursor.execute("ALTER TABLE Enrollment_2023_02 DROP COLUMN SSAStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2023_02 DROP COLUMN FIPSStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2023_02 ADD COLUMN 'Date' DATE DEFAULT '2023-02-15'")
	cursor.execute("ALTER TABLE Enrollment_2023_02 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Enrollment_2023_02 SET 'contractid_planid' = contractid || '' || planid")
	cursor.execute("ALTER TABLE Contract_2023_02 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Contract_2023_02 SET 'contractid_planid' = contractid || '' || planid")
	connection.commit()
	play_successful_message()

	import_contract_2023_01()
	import_enrollment_2023_01()
	cursor.execute("DELETE FROM Enrollment_2023_01 WHERE enrollment = '*'")
	cursor.execute("DELETE FROM Enrollment_2023_01 WHERE enrollment = 'Enrollment'")
	cursor.execute("ALTER TABLE Enrollment_2023_01 DROP COLUMN SSAStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2023_01 DROP COLUMN FIPSStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2023_01 ADD COLUMN 'Date' DATE DEFAULT '2023-01-15'")
	cursor.execute("ALTER TABLE Enrollment_2023_01 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Enrollment_2023_01 SET 'contractid_planid' = contractid || '' || planid")
	cursor.execute("ALTER TABLE Contract_2023_01 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Contract_2023_01 SET 'contractid_planid' = contractid || '' || planid")
	connection.commit()
	play_successful_message()

	import_contract_2022_12()
	import_enrollment_2022_12()
	cursor.execute("DELETE FROM Enrollment_2022_12 WHERE enrollment = '*'")
	cursor.execute("DELETE FROM Enrollment_2022_12 WHERE enrollment = 'Enrollment'")
	cursor.execute("ALTER TABLE Enrollment_2022_12 DROP COLUMN SSAStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_12 DROP COLUMN FIPSStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_12 ADD COLUMN 'Date' DATE DEFAULT '2022-12-15'")
	cursor.execute("ALTER TABLE Enrollment_2022_12 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Enrollment_2022_12 SET 'contractid_planid' = contractid || '' || planid")
	cursor.execute("ALTER TABLE Contract_2022_12 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Contract_2022_12 SET 'contractid_planid' = contractid || '' || planid")
	connection.commit()
	play_successful_message()

	import_contract_2022_11()
	import_enrollment_2022_11()
	cursor.execute("DELETE FROM Enrollment_2022_11 WHERE enrollment = '*'")
	cursor.execute("DELETE FROM Enrollment_2022_11 WHERE enrollment = 'Enrollment'")
	cursor.execute("ALTER TABLE Enrollment_2022_11 DROP COLUMN SSAStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_11 DROP COLUMN FIPSStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_11 ADD COLUMN 'Date' DATE DEFAULT '2022-11-15'")
	cursor.execute("ALTER TABLE Enrollment_2022_11 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Enrollment_2022_11 SET 'contractid_planid' = contractid || '' || planid")
	cursor.execute("ALTER TABLE Contract_2022_11 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Contract_2022_11 SET 'contractid_planid' = contractid || '' || planid")
	connection.commit()
	play_successful_message()

	import_contract_2022_10()
	import_enrollment_2022_10()
	cursor.execute("DELETE FROM Enrollment_2022_10 WHERE enrollment = '*'")
	cursor.execute("DELETE FROM Enrollment_2022_10 WHERE enrollment = 'Enrollment'")
	cursor.execute("ALTER TABLE Enrollment_2022_10 DROP COLUMN SSAStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_10 DROP COLUMN FIPSStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_10 ADD COLUMN 'Date' DATE DEFAULT '2022-10-15'")
	cursor.execute("ALTER TABLE Enrollment_2022_10 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Enrollment_2022_10 SET 'contractid_planid' = contractid || '' || planid")
	cursor.execute("ALTER TABLE Contract_2022_10 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Contract_2022_10 SET 'contractid_planid' = contractid || '' || planid")
	connection.commit()
	play_successful_message()

	import_contract_2022_09()
	import_enrollment_2022_09()
	cursor.execute("DELETE FROM Enrollment_2022_09 WHERE enrollment = '*'")
	cursor.execute("DELETE FROM Enrollment_2022_09 WHERE enrollment = 'Enrollment'")
	cursor.execute("ALTER TABLE Enrollment_2022_09 DROP COLUMN SSAStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_09 DROP COLUMN FIPSStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_09 ADD COLUMN 'Date' DATE DEFAULT '2022-09-15'")
	cursor.execute("ALTER TABLE Enrollment_2022_09 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Enrollment_2022_09 SET 'contractid_planid' = contractid || '' || planid")
	cursor.execute("ALTER TABLE Contract_2022_09 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Contract_2022_09 SET 'contractid_planid' = contractid || '' || planid")
	connection.commit()
	play_successful_message()

	import_contract_2022_08()
	import_enrollment_2022_08()
	cursor.execute("DELETE FROM Enrollment_2022_08 WHERE enrollment = '*'")
	cursor.execute("DELETE FROM Enrollment_2022_08 WHERE enrollment = 'Enrollment'")
	cursor.execute("ALTER TABLE Enrollment_2022_08 DROP COLUMN SSAStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_08 DROP COLUMN FIPSStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_08 ADD COLUMN 'Date' DATE DEFAULT '2022-08-15'")
	cursor.execute("ALTER TABLE Enrollment_2022_08 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Enrollment_2022_08 SET 'contractid_planid' = contractid || '' || planid")
	cursor.execute("ALTER TABLE Contract_2022_08 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Contract_2022_08 SET 'contractid_planid' = contractid || '' || planid")
	connection.commit()
	play_successful_message()

	import_contract_2022_07()
	import_enrollment_2022_07()
	cursor.execute("DELETE FROM Enrollment_2022_07 WHERE enrollment = '*'")
	cursor.execute("DELETE FROM Enrollment_2022_07 WHERE enrollment = 'Enrollment'")
	cursor.execute("ALTER TABLE Enrollment_2022_07 DROP COLUMN SSAStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_07 DROP COLUMN FIPSStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_07 ADD COLUMN 'Date' DATE DEFAULT '2022-07-15'")
	cursor.execute("ALTER TABLE Enrollment_2022_07 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Enrollment_2022_07 SET 'contractid_planid' = contractid || '' || planid")
	cursor.execute("ALTER TABLE Contract_2022_07 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Contract_2022_07 SET 'contractid_planid' = contractid || '' || planid")
	connection.commit()
	play_successful_message()

	import_contract_2022_06()
	import_enrollment_2022_06()
	cursor.execute("DELETE FROM Enrollment_2022_06 WHERE enrollment = '*'")
	cursor.execute("DELETE FROM Enrollment_2022_06 WHERE enrollment = 'Enrollment'")
	cursor.execute("ALTER TABLE Enrollment_2022_06 DROP COLUMN SSAStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_06 DROP COLUMN FIPSStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_06 ADD COLUMN 'Date' DATE DEFAULT '2022-06-15'")
	cursor.execute("ALTER TABLE Enrollment_2022_06 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Enrollment_2022_06 SET 'contractid_planid' = contractid || '' || planid")
	cursor.execute("ALTER TABLE Contract_2022_06 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Contract_2022_06 SET 'contractid_planid' = contractid || '' || planid")
	connection.commit()
	play_successful_message()

	import_contract_2022_05()
	import_enrollment_2022_05()
	cursor.execute("DELETE FROM Enrollment_2022_05 WHERE enrollment = '*'")
	cursor.execute("DELETE FROM Enrollment_2022_05 WHERE enrollment = 'Enrollment'")
	cursor.execute("ALTER TABLE Enrollment_2022_05 DROP COLUMN SSAStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_05 DROP COLUMN FIPSStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_05 ADD COLUMN 'Date' DATE DEFAULT '2022-05-15'")
	cursor.execute("ALTER TABLE Enrollment_2022_05 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Enrollment_2022_05 SET 'contractid_planid' = contractid || '' || planid")
	cursor.execute("ALTER TABLE Contract_2022_05 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Contract_2022_05 SET 'contractid_planid' = contractid || '' || planid")
	connection.commit()
	play_successful_message()

	import_contract_2022_04()
	import_enrollment_2022_04()
	cursor.execute("DELETE FROM Enrollment_2022_04 WHERE enrollment = '*'")
	cursor.execute("DELETE FROM Enrollment_2022_04 WHERE enrollment = 'Enrollment'")
	cursor.execute("ALTER TABLE Enrollment_2022_04 DROP COLUMN SSAStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_04 DROP COLUMN FIPSStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_04 ADD COLUMN 'Date' DATE DEFAULT '2022-04-15'")
	cursor.execute("ALTER TABLE Enrollment_2022_04 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Enrollment_2022_04 SET 'contractid_planid' = contractid || '' || planid")
	cursor.execute("ALTER TABLE Contract_2022_04 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Contract_2022_04 SET 'contractid_planid' = contractid || '' || planid")
	connection.commit()
	play_successful_message()

	import_contract_2022_03()
	import_enrollment_2022_03()
	cursor.execute("DELETE FROM Enrollment_2022_03 WHERE enrollment = '*'")
	cursor.execute("DELETE FROM Enrollment_2022_03 WHERE enrollment = 'Enrollment'")
	cursor.execute("ALTER TABLE Enrollment_2022_03 DROP COLUMN SSAStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_03 DROP COLUMN FIPSStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_03 ADD COLUMN 'Date' DATE DEFAULT '2022-03-15'")
	cursor.execute("ALTER TABLE Enrollment_2022_03 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Enrollment_2022_03 SET 'contractid_planid' = contractid || '' || planid")
	cursor.execute("ALTER TABLE Contract_2022_03 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Contract_2022_03 SET 'contractid_planid' = contractid || '' || planid")
	connection.commit()
	play_successful_message()

	import_contract_2022_02()
	import_enrollment_2022_02()
	cursor.execute("DELETE FROM Enrollment_2022_02 WHERE enrollment = '*'")
	cursor.execute("DELETE FROM Enrollment_2022_02 WHERE enrollment = 'Enrollment'")
	cursor.execute("ALTER TABLE Enrollment_2022_02 DROP COLUMN SSAStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_02 DROP COLUMN FIPSStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_02 ADD COLUMN 'Date' DATE DEFAULT '2022-02-15'")
	cursor.execute("ALTER TABLE Enrollment_2022_02 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Enrollment_2022_02 SET 'contractid_planid' = contractid || '' || planid")
	cursor.execute("ALTER TABLE Contract_2022_02 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Contract_2022_02 SET 'contractid_planid' = contractid || '' || planid")
	connection.commit()
	play_successful_message()

	import_contract_2022_01()
	import_enrollment_2022_01()
	cursor.execute("DELETE FROM Enrollment_2022_01 WHERE enrollment = '*'")
	cursor.execute("DELETE FROM Enrollment_2022_01 WHERE enrollment = 'Enrollment'")
	cursor.execute("ALTER TABLE Enrollment_2022_01 DROP COLUMN SSAStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_01 DROP COLUMN FIPSStateCountyCode")
	cursor.execute("ALTER TABLE Enrollment_2022_01 ADD COLUMN 'Date' DATE DEFAULT '2022-01-15'")
	cursor.execute("ALTER TABLE Enrollment_2022_01 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Enrollment_2022_01 SET 'contractid_planid' = contractid || '' || planid")
	cursor.execute("ALTER TABLE Contract_2022_01 ADD COLUMN 'contractid_planid' text")
	cursor.execute("UPDATE Contract_2022_01 SET 'contractid_planid' = contractid || '' || planid")
	connection.commit()
	play_successful_message()
	
	#cursor.execute("INSERT INTO Master * FROM enrollment_2023_05 INNER JOIN contract_2023_05 ON enrollment_2023_05.contractid_planid = contract_2023_05.contractid_planid")


if __name__ == "__main__":
	app()
